SET SCHEMA FN45309;

--Function 1
drop function get_customer;

CREATE FUNCTION get_customer(target_id INTEGER)
RETURNS TABLE(phone char(10), e_mail varchar(100))
RETURN
    SELECT PHONE, E_MAIL
    FROM CUSTOMER
    WHERE CUSTOMER.ID = target_id;

SELECT * FROM TABLE(FN45309.get_customer(2));


--Function 2
drop function get_orders_from_customer;

CREATE FUNCTION get_orders_from_customer(targed_id INTEGER)
RETURNS TABLE (TOTAL_PRICE int, SHIPPING_ADDRESS varchar(100), STATUS varchar(30), ORDER_DATE date)
return
    SELECT  TOTAL_PRICE, SHIPPING_ADDRESS, STATUS, ORDER_DATE
    FROM ORDERS
    where ORDERS.CUSTOMER_ID = targed_id;

SELECT * FROM TABLE(FN45309.get_orders_from_customer(3));


--Function 3
CREATE FUNCTION GET_TOTAL_PRICE_FOR_CUSTOMER(F_PHONE CHAR(10))
RETURNS INTEGER
RETURN
    SELECT SUM(TOTAL_PRICE)
    FROM ORDERS JOIN CUSTOMER C2 on ORDERS.CUSTOMER_ID = C2.ID
    WHERE C2.PHONE = F_PHONE AND (STATUS = 'SENT' OR STATUS = 'IN PROCESS');

VALUES FN45309.GET_TOTAL_PRICE_FOR_CUSTOMER('0878452318');


--Function 4
CREATE FUNCTION GET_CATEGORY_BY_TYPE(desc varchar(100))
RETURNS INT
RETURN SELECT id
       FROM CATEGORY as ctg
       WHERE ctg.CATEGORY_TYPE = desc;

VALUES  FN45309.GET_CATEGORY_BY_TYPE('Monitors');
